USE [master]
GO

/****** Object:  Database [SpringDao]    Script Date: 29/12/2015 22:15:55 ******/
CREATE DATABASE [SpringDao]
GO

ALTER DATABASE [SpringDao] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SpringDao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SpringDao] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [SpringDao] SET ANSI_NULLS OFF
GO

ALTER DATABASE [SpringDao] SET ANSI_PADDING OFF
GO

ALTER DATABASE [SpringDao] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [SpringDao] SET ARITHABORT OFF
GO

ALTER DATABASE [SpringDao] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [SpringDao] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [SpringDao] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [SpringDao] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [SpringDao] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [SpringDao] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [SpringDao] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [SpringDao] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [SpringDao] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [SpringDao] SET  DISABLE_BROKER
GO

ALTER DATABASE [SpringDao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [SpringDao] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [SpringDao] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [SpringDao] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [SpringDao] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [SpringDao] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [SpringDao] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [SpringDao] SET RECOVERY SIMPLE
GO

ALTER DATABASE [SpringDao] SET  MULTI_USER
GO

ALTER DATABASE [SpringDao] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [SpringDao] SET DB_CHAINING OFF
GO

ALTER DATABASE [SpringDao] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [SpringDao] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [SpringDao] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [SpringDao] SET  READ_WRITE
GO

